# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'BeersListDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeersListDemo
  pod 'Alamofire', '4.9.1'
  pod 'Moya', '13.0.1'
  pod 'ReachabilitySwift', '5.0.0'
  # layout
  pod 'SnapKit'
  # image
  pod 'Kingfisher'
  # OC
  pod 'MBProgressHUD'
  pod 'MJRefresh','3.7.2'
end
